### ISSUE TITLE
Importar o projeto Atividade8 

### ISSUE THREAD

**Issue by nicholsZ** [nicholsZ/AtividadeA8-GrupoN#2]
Os membros deverão "Importar" o projeto Atividade8 do repositório AtividadeA8-GrupoN.

**Comment by nicholsx** [comment]
Projeto Importado!

**Comment by brunoqp78** [comment]
Irei fechar a issue, utilizando o comentário no commit. close #2.

**Comment by brunoqp78** [comment]
Irei fechar a Issue... ela poderia ter sido fechada quando deu algum commit no git. Mas podemos fechar aqui.
