### ISSUE TITLE
 Criar a classe EmpregadoTerceirizadoTest.

### ISSUE THREAD

**Issue by nicholsZ** [nicholsZ/AtividadeA8-GrupoN#7]
Criar a classe EmpregadoTerceirizadoTest.

**Comment by brunoqp78** [comment]
Tente reabrir uma atividade e fechá-la utilizando o comentário do commit.

**Comment by nicholsZ** [comment]
Bruno elas estão sendo fechadas automaticamente, pelo comentário do commit do Eclipse com Ex: (Comentario) e no final close #7

**Comment by brunoqp78** [comment]
Blz

Em sex., 2 de jul. de 2021 20:50, nicholsZ ***@***.***>
escreveu:
